### ISSUE TITLE
Suggestion: always show results

### ISSUE THREAD

**Issue by HermansJarno** [MicroFocus/bdd2octane#27]
Currently we have some feature files with the Rule tag, which are not yet supported (if im not mistaken).
These feature files cause following error:

Exception in thread "main" java.lang.RuntimeException: when using BUT, AND flowContext should not be empty
	at com.microfocus.bdd.gherkin.GherkinScenario.updateFlowContext(GherkinScenario.java:87)
	at com.microfocus.bdd.gherkin.GherkinScenario.lambda$initialize$0(GherkinScenario.java:62)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.microfocus.bdd.gherkin.GherkinScenario.initialize(GherkinScenario.java:61)
	at com.microfocus.bdd.gherkin.GherkinScenario.<init>(GherkinScenario.java:55)
	at com.microfocus.bdd.gherkin.GherkinFeature.lambda$initialize$0(GherkinFeature.java:75)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.microfocus.bdd.gherkin.GherkinFeature.initialize(GherkinFeature.java:66)
	at com.microfocus.bdd.gherkin.GherkinFeature.<init>(GherkinFeature.java:60)
	at com.microfocus.bdd.util.GherkinDocumentUtil.getFeature(GherkinDocumentUtil.java:90)
	at com.microfocus.bdd.util.GherkinDocumentUtil.generateSkeletonFeature(GherkinDocumentUtil.java:58)
	at com.microfocus.bdd.FeatureFileLocator.parseFeatureFile(FeatureFileLocator.java:179)
	at com.microfocus.bdd.FeatureFileLocator.getOctaneFeature(FeatureFileLocator.java:108)
	at com.microfocus.bdd.OctaneFeatureLocator.lambda$createOctaneFeatureIfNotCached$1(OctaneFeatureLocator.java:84)
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
	at com.microfocus.bdd.OctaneFeatureLocator.createOctaneFeatureIfNotCached(OctaneFeatureLocator.java:83)
	at com.microfocus.bdd.OctaneFeatureLocator.getOctaneFeatureByName(OctaneFeatureLocator.java:56)
	at com.microfocus.bdd.CucumberJvmHandler.getFeatureName(CucumberJvmHandler.java:197)
	at com.microfocus.bdd.Bdd2Octane.run(Bdd2Octane.java:102)
	at com.microfocus.bdd.App.main(App.java:62)
	
The error itself is not why i create this issue. 
The error currently blocks report creation for all other feature files aswell.
It would be nice if despite syntax errors are present in a feature file, other feature files, which were ok, are still present in the feature file.

We also tried to ignore the feature files with syntax errors (because of the unsupported Rule tag) with an annotation but this didnt help.

Please make a new version of bdd2octane where all successful test results are reported and syntax errors are either reported or ignored. This way we always get test results.

Now if an error occurs we get this report file:

```
<?xml version="1.0" ?>
<!--Generated by bdd2octane 1.1.8-->
<features version="1">
```

**Comment by micheleh** [comment]
@HermansJarno, could you please post a minimal feature file that produces that exception?
@nissimshitrit

**Comment by HermansJarno** [comment]
I need to correct my previous statement. We are almost certain that this causes the problem:

`Feature: My feature
  Background:
    Given something
 
  Scenario: My scenario
    And something else
    When this
    Then that
    And also this`
    
 A scenario that starts with an And because the Background already has a Given. This is also not possible in octane UI (we are still migrating our feature files from git to Octane).

**Comment by micheleh** [comment]
@HermansJarno, I asked Copilot the following: 
_Find an example for a gherkin scenario that the first scenario line begins with "And"_
The reply was:

> Finding an example where a Gherkin scenario starts with "And" is quite unusual, as it's not standard practice. Typically, scenarios start with **Scenario:** followed by steps that begin with **Given**, **When**, **Then**, **And**, or **But**. However, for educational purposes, here's a contrived example:

```gherkin
Feature: User Login

Scenario: Successful login
  And the user is on the login page
  When the user enters valid credentials
  And clicks the login button
  Then the user should be redirected to the dashboard
```

> In this example, the scenario starts with "And," but it's important to note that this is not recommended. The first step should ideally set the context with **Given** or **When** to make the scenario clearer and more understandable.


So, although the Gherkin language syntax does not forbid it, I suggest avoiding using "And" as the first keyword of a scenario.
If you are migrating your scripts from git to Octane, maybe as part of the effort, you can replace every "And" in the first line of a scenario with "Given".

**Comment by HermansJarno** [comment]
Understood, thank you.
